# Solving Linear Equations

## 2.1 Vector and Linear Equations

### Contents

#### Matlab  vs numpy matrix operation and handling 
One key reference is from numpy doc: [numpy for matlab users](https://docs.scipy.org/doc/numpy-1.15.0/user/numpy-for-matlab-users.html)

In [34]:
import numpy as np
# Matrix definition
# vs Matlab: a = [1 2 3 4]; b = [5 6 7 8];
a = np.array([1,2,3,4]); b = np.array([5,6,7,8])
#A = [1 2 3; 2 5 2; 6 -3 1] ;x=[0;0;2]
A = np.array([[1,2,3],[2,5,2],[6,-3,1]]); x = np.array([0,0,2])
# Matrix pickup with row, column
# vs Matlab: a(1),a(:,1), a(0,0)
A[0], A[:,0], A[0][0]

# dot mutiply
# vs Matlab: a .* b
np.dot(A,x)

print(A)
print(A*x)
print(np.dot(A,x))
A[0], A[:,0], A[0][1]

[[ 1  2  3]
 [ 2  5  2]
 [ 6 -3  1]]
[[0 0 6]
 [0 0 4]
 [0 0 2]]
[6 4 2]


(array([1, 2, 3]), array([1, 2, 6]), 2)